spring:
  application:
    name: webmagic
  jpa:
    database: mysql
    open-in-view: true
    show-sql: true
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
server:
  port: 8080